repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      # - id: terraform_tfsec
      # - id: terraform_docs
      # - id: terraform_checkov
      # - id: terrascan
      # - id: tfupdate
