name: Release CI

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-reusable.yaml
    secrets: inherit
    with:
      project-name: mmw
      fd-aws-tf-modules-version: v2.23.0
