name: Release CI

env:
  PROJECT_NAME: mmw
  FILMDROP_TERRAFORM_RELEASE: v2.23.0 # keep this up to date!
  
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-reusable.yaml
    secrets: inherit
    environment:
      name: staging
      url: https://tiler.staging.modelmywatershed.org
    with:
      project-name: ${{ env.PROJECT_NAME }}
      stage: staging
      fd-aws-tf-modules-version: ${{ env.FILMDROP_TERRAFORM_RELEASE }}

  deploy-prod:
    uses: ./.github/workflows/deploy-reusable.yaml
    secrets: inherit
    environment:
      name: prod
      url: https://tiler.modelmywatershed.org
    with:
      project-name: ${{ env.PROJECT_NAME }}
      stage: staging
      fd-aws-tf-modules-version: ${{ env.FILMDROP_TERRAFORM_RELEASE }}
