name: 🚀 Deploy Prod

on:
  push:
    tags:        
      - v.*

jobs:
  deploy-prod:
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit
    concurrency: prod
    with:
      stage: prod
      url: https://console.modelmywatershed.org
      fd-aws-tf-modules-version: v2.23.0
