name: 🚀 Deploy

on:
  push:
    branches: ["main", "pv/reusable"]
    tags: ["v*.*.*"]

jobs:
  deploy-staging:
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit
    concurrency: staging
    with:
      stage: staging
      url: https://console.staging.modelmywatershed.org
      fd-aws-tf-modules-version: v2.23.0

  deploy-prod:
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit
    concurrency: prod
    with:
      stage: prod
      url: https://console.modelmywatershed.org
      fd-aws-tf-modules-version: v2.23.0
